---
name: CI + CD
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Compile
        run: echo Hello, world!
        

  DeployQA:
    name: Deploy to QA
    if: github.event_name == 'pull_request'
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: QA
      url: ${{ steps.urls.outputs.qa_url }}
    steps:
      - name: Deploy
        run: echo I am deploying!

      - name: Setup urls
        id: urls
        run: |
          echo "Setup environment URLs"
          echo "qa_url=https://qa-${{ secrets.ENV_URL }}.com" >> $GITHUB_OUTPUT        

  DeployStaging:
    name: Deploy to Staging
    if: github.event.ref == 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: STG
      url: ${{ steps.urls.outputs.stg_url }}

    steps:
      - name: Deploy
        run: echo I am deploying!

      - name: Setup urls
        id: urls
        run: |
          echo "Setup environment URLs"
          echo "stg_url=https://stg-${{ secrets.ENV_URL }}.com" >> $GITHUB_OUTPUT

  DeployProd:
    name: Deploy to Production
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment:
      name: PROD
      url: ${{ steps.urls.outputs.prod_url }}
    steps:
      - name: Deploy
        run: echo I am deploying!

      - name: Setup urls
        id: urls
        run: |
          echo "Setup environment URLs"
          echo "prod_url=https://${{ secrets.ENV_URL }}.com" >> $GITHUB_OUTPUT        
