---
name: CI + CD
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Compile
        run: echo Hello, world!
        
  SetupEnvironmentUrls:
    runs-on: ubuntu-latest
    outputs:
      qa_url: https://${{ format('qa.{0}', secrets.ENV_URL) }}.com
      staging_url: https://${{ format('stg.{0}', secrets.ENV_URL) }}.com
      prod_url: https://${{ secrets.ENV_URL }}.com
    steps:
      - run: echo "Setup environment URLs"

  DeployQA:
    name: Deploy to QA
    if: github.event_name == 'pull_request'
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: QA
      url: ${{ needs.SetupEnvironmentUrls.outputs.qa_url }}
    steps:
      - name: Deploy
        run: echo I am deploying!

  DeployStaging:
    name: Deploy to Staging
    if: github.event.ref == 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: ${{ needs.SetupEnvironmentUrls.outputs.staging_url }}
    steps:
      - name: Deploy
        run: echo I am deploying!

  DeployProd:
    name: Deploy to Production
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: ${{ needs.SetupEnvironmentUrls.outputs.prod_url }}
    steps:
      - name: Deploy
        run: echo I am deploying!